SELECT * FROM ADDRESSES;

SELECT * FROM STUDENTS;

SELECT STUD_ID AS studId, NAME, EMAIL, PHONE, DOB
  FROM STUDENTS
 WHERE STUD_ID = 1;

SELECT STUD_ID, NAME, EMAIL, DOB,
		SUBSTR(PHONE, 1, 3) AS F,
		SUBSTR(PHONE, 5, 3) AS M,
		SUBSTR(PHONE, 9, 4) AS L
  FROM STUDENTS
 WHERE STUD_ID = 1;

SELECT STUD_ID AS studId, NAME, EMAIL, PHONE, DOB FROM STUDENTS;

SELECT STUD_ID AS studId, NAME, EMAIL, PHONE, DOB, GENDER FROM STUDENTS;

INSERT INTO STUDENTS(STUD_ID, NAME, EMAIL, PHONE, DOB)
VALUES 

DELETE
  FROM STUDENTS
 WHERE STUD_ID = 3;

UPDATE STUDENTS
   SET NAME = , EMAIL = , PHONE = , DOB = 
 WHERE STUD_ID = 3;

SELECT STUD_ID, NAME, EMAIL, PHONE, DOB, A.ADDR_ID, STREET, CITY, STATE, ZIP, COUNTRY
  FROM STUDENTS S JOIN ADDRESSES A ON S.ADDR_ID = A.ADDR_ID
 WHERE STUD_ID = 1;

SELECT * FROM TUTORS;

SELECT T.TUTOR_ID, T.NAME AS TUTOR_NAME, EMAIL, C.COURSE_ID, C.NAME, DESCRIPTION, START_DATE, END_DATE
  FROM TUTORS T LEFT OUTER JOIN COURSES C ON T.TUTOR_ID = C.TUTOR_ID
 WHERE T.TUTOR_ID = 1;

INSERT INTO TUTORS(TUTOR_ID, NAME, EMAIL, PHONE, ADDR_ID)
VALUES (#{tutorId}, #{name}, #{email}, #{phone}, #{address.addrId})

DELETE FROM TUTORS
 WHERE TUTOR_ID = #{tutorId}

SELECT * FROM COURSES;

SELECT COURSE_ID, NAME, DESCRIPTION, START_DATE, END_DATE, TUTOR_ID FROM COURSES;

DELETE FROM COURSES
WHERE COURSE_ID = 6;

INSERT INTO COURSES(COURSE_ID, NAME, DESCRIPTION, START_DATE, END_DATE, TUTOR_ID)
VALUES (#{courseId}, #{name}, #{description}, #{startDate}, #{endDate}, #{tutorId})

DELETE FROM COURSES
 WHERE COURSE_ID IN (4, 5, 6);

SELECT * FROM COURSE_ENROLLMENT;

SELECT * FROM USER_PICS;

INSERT INTO USER_PICS(NAME, PIC, BIO)
VALUES ('TENET1', NULL, NULL);

SELECT ID, NAME, PIC, BIO
  FROM USER_PICS
 WHERE ID = #{id};

DELETE FROM USER_PICS
 WHERE ID = 2;

