SELECT * FROM ADDRESSES;

SELECT * FROM STUDENTS;

SELECT STUD_ID AS studId, NAME, EMAIL, PHONE, DOB
  FROM STUDENTS
 WHERE STUD_ID = 1;

SELECT STUD_ID, NAME, EMAIL, DOB,
		SUBSTR(PHONE, 1, 3) AS F,
		SUBSTR(PHONE, 5, 3) AS M,
		SUBSTR(PHONE, 9, 4) AS L
  FROM STUDENTS
 WHERE STUD_ID = 1;

SELECT STUD_ID AS studId, NAME, EMAIL, PHONE, DOB FROM STUDENTS;

INSERT INTO STUDENTS(STUD_ID, NAME, EMAIL, PHONE, DOB)
VALUES 

DELETE
  FROM STUDENTS
 WHERE STUD_ID = 3;

UPDATE STUDENTS
   SET NAME = , EMAIL = , PHONE = , DOB = 
 WHERE STUD_ID = 3;

SELECT STUD_ID, NAME, EMAIL, PHONE, DOB, A.ADDR_ID, STREET, CITY, STATE, ZIP, COUNTRY
  FROM STUDENTS S JOIN ADDRESSES A ON S.ADDR_ID = A.ADDR_ID
 WHERE STUD_ID = 1;

SELECT * FROM TUTORS;

SELECT T.TUTOR_ID, T.NAME AS TUTOR_NAME, EMAIL, C.COURSE_ID, C.NAME, DESCRIPTION, START_DATE, END_DATE
  FROM TUTORS T LEFT OUTER JOIN COURSES C ON T.TUTOR_ID = C.TUTOR_ID
 WHERE T.TUTOR_ID = 1;

SELECT * FROM COURSES;

SELECT * FROM COURSE_ENROLLMENT;
